# Generated by Django 5.0.3 on 2024-03-22 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_alter_user_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
    ]
