# Generated by Django 5.0.3 on 2024-04-21 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_degree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='degree',
            field=models.CharField(max_length=255),
        ),
    ]
