# Generated by Django 5.0.3 on 2024-05-01 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(default='L', max_length=255),
        ),
    ]
