# Generated by Django 5.0.3 on 2024-03-14 07:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alt', models.CharField(max_length=225)),
                ('src', models.ImageField(blank=True, upload_to='uploads/%Y/%m/%d')),
            ],
        ),
    ]
