# Generated by Django 5.0.3 on 2024-03-14 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_alter_feedback_user'),
        ('resource', '0003_image_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='feedback',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_image', to='feedback.feedback'),
        ),
    ]
