# Generated by Django 5.0.3 on 2024-04-07 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(default='Chưa duyệt', max_length=255),
        ),
    ]
