# Generated by Django 5.0.3 on 2024-04-28 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_donantionproduct'),
        ('product', '0009_product_gender'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='donantionproduct',
            unique_together={('product', 'event')},
        ),
    ]
